<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FluxoCaixa.Application\FluxoCaixa.Application.csproj" />
    <ProjectReference Include="..\FluxoCaixa.Domain\FluxoCaixa.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BackgroundServices\" />
    <Folder Include="Configurations\" />
    <Folder Include="Repositories\" />
    <Folder Include="Persistence\" />
  </ItemGroup>

</Project>
